server:
  port: 8080
  servlet:
    context-path: /ishareReading
  # 添加Tomcat异步请求配置
  tomcat:
    threads:
      max: 200 # 最大工作线程数
    connection-timeout: 20000 # 连接超时毫秒
    max-connections: 10000 # 最大连接数
    accept-count: 100 # 等待队列长度
    # 异步请求相关设置
    async-timeout: 300000 # 异步请求超时时间 5分钟

spring:
  application:
    name: back-reading
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:isharereading}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:307314}
  data:
    redis:
      host: localhost
      port: 6379
  threads:
    virtual:
      enabled: true
