server:
  port: 8080
  servlet:
    context-path: /ishareReading
  # 添加Tomcat异步请求配置
  tomcat:
    threads:
      max: 200 # 最大工作线程数
    connection-timeout: 20000 # 连接超时毫秒
    max-connections: 10000 # 最大连接数
    accept-count: 100 # 等待队列长度
    # 异步请求相关设置
    async-timeout: 300000 # 异步请求超时时间 5分钟
spring:
  ai:
    dashscope:
      api-key: sk-9f6e57e4b29540e2958f0a57f71fa143
    openai:
      api-key: sk-9f6e57e4b29540e2958f0a57f71fa143
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: back-reading
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54321}/${DB_NAME:isharereading}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  #    redis配置
  data:

    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
#      host: 118.178.92.216
  elasticsearch:
    uris: ${ES_HOST:http://localhost:9200}
  #      spring servlet 虚拟线程开启
  threads:
    virtual:
      enabled: true
  #      qq邮箱配置
  mail:
    code-validation: 5
    host: smtp.qq.com
    username: mingdongiloveu2@qq.com
    password: bidonaeuubiqchca
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true


#阿里云OSS配置
aliyun:
  oss:
    buckets:
      bankai:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        accessKeyId: LTAI5tRubA1tFPH7RMeSUAPt
        accessKeySecret: ClNjKHKk2BYncyzLg4aJFck1YZyAdy
        bucketName: bankai
jwt:
  config:
    secret: "xyx8BDbRigUDaY6pZFfWus2jZWLPHO"
    expire: 8640000000000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:/org/ishareReading/bankai/mapper/*.xml

