spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://${DATASOURCE_HOST:127.0.0.1:3306}/${DATASOURCE_NAME:ishareReading_test}?serverTimezone=GMT%2B8
    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PASSWORD:123}
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    username: ${MAIL_NAME:3429726418@qq.com}
    password: ${MAIL_PASSWORD:pptzprmteytqdaad}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: ${SERVER_PORT:8888}