server:
  tomcat:
    threads:
      max: 200 # 最大工作线程数
    connection-timeout: 20000 # 连接超时毫秒
    max-connections: 10000 # 最大连接数
    accept-count: 100 # 等待队列长度
    # 异步请求相关设置
    async-timeout: 300000 # 异步请求超时时间 5分钟
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name: agent-reading
  ai:
    vectorstore:
      pgvector:
        dimensions: 1536
    dashscope:
      rerank:
        options:
          model: gte-rerank-v2
        api-key: sk-8b67da98807649bb9886327549af564f
      embedding:
        api-key: sk-8b67da98807649bb9886327549af564f
        options:
          model: text-embedding-v2
          dimensions: 1536
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DASHSCOPE_API_KEY:sk-8b67da98807649bb9886327549af564f}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    openai:
      api-key: sk-9f6e57e4b29540e2958f0a57f71fa143
      base-url: https://api.deepseek.com
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:/org/ishareReading/bankai/mapper/*.xml

