server:
  port: 8080
  servlet:
    context-path: /ishareReading
spring:
  mvc:
    async:
      request-timeout: 60000 # 例如，设置为60秒
  application:
    name: agent-reading
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54321}/${DB_NAME:isharereading}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    vectorstore:
      pgvector:
        dimensions: 1536
    dashscope:
      rerank:
        options:
          model: gte-rerank-v2

      embedding:
        api-key: sk-8b67da98807649bb9886327549af564f
        options:
          model: text-embedding-async-v2
          dimensions: 1536
        base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DASHSCOPE_API_KEY:sk-8b67da98807649bb9886327549af564f}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    openai:
      api-key: sk-9f6e57e4b29540e2958f0a57f71fa143
      base-url: https://api.deepseek.com
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:/org/ishareReading/bankai/mapper/*.xml

