#

server:
  port: 8080
  servlet:
    context-path: /ishareReading
spring:
  application:
    name: agent-reading
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54321}/${DB_NAME:isharereading}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: localhost
      port: 6379
  threads:
    virtual:
      enabled: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  ai:
    dashscope:
      api-key: sk-9f6e57e4b29540e2958f0a57f71fa143
    openai:
      api-key: sk-9f6e57e4b29540e2958f0a57f71fa143
      base-url: https://api.deepseek.com
aliyun:
  oss:
    buckets:
      bankai:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        accessKeyId: LTAI5tRubA1tFPH7RMeSUAPt
        accessKeySecret: ClNjKHKk2BYncyzLg4aJFck1YZyAdy
        bucketName: bankai
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:/org/ishareReading/bankai/mapper/*.xml

