services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reading-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://0.0.0.0:8080}
      - HOST=0.0.0.0
    command: sh -c "npm run dev -- --host 0.0.0.0"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
    