version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker-compose/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:54321/isharereading
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_ELASTICSEARCH_URIS=http://localhost:9200
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379

volumes:
  postgres_data:
  es_data:
  redis_data: 