services:

  redis:
    restart: always
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/quay.io/opstree/redis:v7.0.5
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: redis
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis-stand.conf
    command: redis-server /etc/redis/redis-stand.conf
